name: CodeCov and Vulnerabilities

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.10.7"
      - name: Generate coverage report
        run: |
          pip install .[dev]
          pytest --cov=./src --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:          
          args: --severity-threshold=high 
